CREATE TABLE AKT_TRIP (
    ID UUID PRIMARY KEY,
    DESTINATION VARCHAR(255) NOT NULL,
    START_AT TIMESTAMP NOT NULL,
    END_AT TIMESTAMP NOT NULL,
    CONFIRMED BOOLEAN NOT NULL,
    OWNER_NAME VARCHAR(255) NOT NULL,
    OWNER_EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE AKT_PARTICIPANT (
    ID        UUID PRIMARY KEY,
    NAME      VARCHAR(255),
    EMAIL     VARCHAR(255) NOT NULL,
    CONFIRMED BOOLEAN      NOT NULL,
    TRIP_ID   UUID,
    FOREIGN KEY (TRIP_ID) REFERENCES AKT_TRIP (ID)
);