CREATE TABLE AKT_TRIP (
    ID UUID PRIMARY KEY,
    DESTINATION VARCHAR(255) NOT NULL,
    START_AT TIMESTAMP NOT NULL,
    END_AT TIMESTAMP NOT NULL,
    CONFIRMED BOOLEAN NOT NULL,
    OWNER_NAME VARCHAR(255) NOT NULL,
    OWNER_EMAIL VARCHAR(255) NOT NULL
);